apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-test
  description: test of Gaivota dev Portal
  annotations:
    github.com/project-slug: eudangeld/medcann
    github.com/team-slug: Software
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: Software
  system: base-service
  definition:  |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
